---
- hosts: appserver
  remote_user: pyapp
  tasks:
#  - name: Ensure dependencies installed
#    become: yes
#    apt:
#      name:
#        - zlib-devel 
#        - bzip2 
#        - bzip2-devel 
#        - readline-devel 
#        - sqlite
#        - sqlite-devel 
#        - openssl-devel 
#        - xz 
#        - xz-devel
#        - libffi-devel
#      state: latest
  - name: Copy script from subtree 
    copy:
      src: bin/pyenv-installer/bin/pyenv-installer
      dest: /home/pyapp/pyenv-installer.sh
      owner: pyapp
      mode: u=rwx

      #  - name: Curl bash script for install
      #    become: yes
      #    get_url:
      #      url: https://pyenv.run
      #      dest: /tmp/pyenv-installer.sh
      #      mode: 0755
  
  - name: Execute script
    become: no
    shell: /home/pyapp/pyenv-installer.sh
    #  - name: Add to bashrc
    #    command: echo "export PATH="/home/pyapp/.pyenv/bin:$PATH"\n eval "$(pyenv init -)"\n eval "$(pyenv virtualenv-init -)"" >> ~/.bashrc
  - name: Clear downloaded script
    become: yes
    file:
      path: /home/pyapp/pyenv-installer.sh
      state: absent
