---
- hosts: appserver
  remote_user: pyapp

  tasks:

  - name: Copy files
    copy:
      src: pyenv-installer.sh
      dest: /home/pyapp/pyenv-installer.sh
      owner: pyapp
      mode: u=rwx

  - name: Copy configuration
    copy:
      src: check_n_add.sh
      dest: /home/pyapp/check_n_add.sh
      owner: pyapp
      mode: u=rwx

  - name: Execute script
    become: no
    shell: /home/pyapp/pyenv-installer.sh

  - name: Configurations
    become: no
    shell: /home/pyapp/check_n_add.sh

  - name: Clear installer script
    become: yes
    file:
      path: /home/pyapp/pyenv-installer.sh
      state: absent

  - name: Clear config verification script
    become: yes
    file:
      path: /home/pyapp/check_n_add.sh
      state: absent
      
      
      
    #    command: echo "export PATH="/home/pyapp/.pyenv/bin:$PATH"\n eval "$(pyenv init -)"\n eval "$(pyenv virtualenv-init -)"" >> ~/.bashrc
